### ISSUE TITLE
Using onKeyDown/onKeyPress to submit form

### ISSUE THREAD

**Issue by SachaG** [hibiken/react-places-autocomplete#208]
I know the enter key is currently used to select a suggestion when browsing through the list, but what would be the best way to use it to submit the entire form itself after the suggestion has been selected?

**Comment by SachaG** [comment]
Here's the solution I found. Feels like there should be an easier way though?

```js
const inputProps = getInputProps({ placeholder: locationPlaceholder });

const onKeyDown = (event) => {
  const suggestionsOpen = !!suggestions.length; // find out if suggestions are active or not
  inputProps.onKeyDown(event); // do the normal onKeyDown callback
  if(!suggestionsOpen && event.keyCode === 13){ // if this is enter key, submit form
    this.submitForm(); 
  }
}
```

And then:

```
<input type="text" {...inputProps} onKeyDown={onKeyDown} />
```

**Comment by sambokai** [comment]
The "official" solution. We might want to document this.

```js
const handleSelect = async (address, placeId, suggestion) => {
    if (!placeId){
         // This code runs when you press enter without having a suggestion selected
    } 
};

<PlacesAutocomplete onSelect={handleSelect}>
...
</PlacesAutocomplete>
```

**Comment by cpertile** [comment]
@sambokai Hey there! Just wanted to point out that your post above saved me right now.

Use case: we're building an Address Autocomplete input that should only work with Australian addresses. We set `componentRestrictions: { country: ['au'] }`, but the QA team found out that if we type something and press Enter before the API call returns with the suggestions, the `handleSelect` is triggered, and in our case, `geocodeByAddress` is also triggered, searching for an address in the US.

We were trying to add eventListeners to the input in order to block the Enter key, but I guess you can imagine how painful that was going.

So thank you for your post.
