### ISSUE TITLE
How to disable autohide of suggestions? i want to show suggestions until user take action on it.

### ISSUE THREAD

**Issue by suyesh** [hibiken/react-places-autocomplete#229]

**Comment by CoVoCre** [comment]
Hey @suyesh,
I guess we'd have to implement a more controlled component, with a feature like a showSuggestion prop that we could control, and that would dictate, above others when to show the suggestions.

**Comment by CoVoCre** [comment]
I looked at your PR, but I was wondering what's causing the keyboard to disappear ? A click on the page, not on the suggestions of course, from the user ? 
I tried to replicate this, and I found that if I use the Android back button, the keyboard disappears but the dropdown stays. This is how dropdowns usually work on internet I think... And how android works...   Just go to goole.com on android, landscape, same for the suggestions when you type a search ! The dropdown with the suggestions disappears if you click anywhere but the dropdown, and the way to hide the keyboard and still keep the dropdown is the back button.
Assuming google though of that, it might actually be less confusing to keep the current behavior, what do you think ? Doesn't mean that this feature is not great though ;) Just keep in mind for your users it might be worse to keep an open dropdown except if they select a suggestion. What if they do not find a good result ? They'd be forced to select one for the dropdown to disappear 😬

I think for these edge cases, we should really provide this showSuggestion prop, so that we could pass our own event handlers or other preferred things...
