### ISSUE TITLE
Nothing appears when I'm typing into the <input /> field

### ISSUE THREAD

**Issue by maelfosso** [hibiken/react-places-autocomplete#241]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I copy the example at README.md but when I type the place, nothing appears even the letter I'm I appear. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I'm expecting to see what I'm typing and the search result.

**Which versions of ReactPlacesAutocomplete, and which browser / OS are affected by this issue?**
ReactPlacesAutocomplete: 7.2.0
Browser: Chronium 69
OS: Debian 9

**Comment by Duckwings** [comment]
Have you try on another browser ?

**Comment by maelfosso** [comment]
Yes @Duckwings 
I tried on Chromium and Firefox. 

Please, I put attached the file. 
[index.js.zip](https://github.com/hibiken/react-places-autocomplete/files/2422417/index.js.zip)

**Comment by Duckwings** [comment]
your handlechange function should change the from state because you set the PlaceAutocomplete value to this.state.from. I dont know what the from.address ( this.setState({ "from.address" : address }); ) mean, but try to replace the this.setState({"from.address": address}) by this.setState({from: address})

**Comment by maelfosso** [comment]
Thank you. I solve it.
