### ISSUE TITLE
Places API token changes for every character entered

### ISSUE THREAD

**Issue by mkoci** [hibiken/react-places-autocomplete#263]
According to [Googles Places Docs](https://developers.google.com/places/web-service/session-tokens) you must specify a 'sessionToken' for every suggestion call. When an address is selected, the sessionToken is expired and you are charged for the suggestion.

After looking at the payloads sent to the places API, this component seems to send a unique 'token' with every onChange event. Am I wrong to think that this would rack up billing costs?

If we can confirm that this is not ideal, I could open a PR and attempt a fix.

Cheers

**Comment by michebble** [comment]
Did anything come of this? Looks like there has been no action taken to incorporate `sessionToken`

**Comment by GWSzeto** [comment]
Hey I'm running into the same issue, I implemented the session Token above as so

```javascript
const sessionToken = new.google.maps.places.AutocompleteSessionToken()

...

<PlacesAutocomplete
    searchOptions={{ sessionToken }}
    {...rest}
>
```
and even after that I saw that it was sending a request after every keystroke to the places api. I also console logged to see if the session token was being generated correctly, which I believe it was.

![Screenshot from 2019-07-23 21-36-27](https://user-images.githubusercontent.com/25385051/61758264-132c1f80-ad92-11e9-90b3-5100362ef432.png)

Do you know what my problem might be @michebble

**Comment by TroyWolf** [comment]
What @mkoci reports sounds serious to me---admittedly a newb to this package and the Places API in general. However, what I read is that you create a session token for each autocomplete "session". That is, all the keystroke calls to do the lookups. When the user selects a match, you use that same token for the final "detail" request. Then for subsequent autocomplete sessions, you must generate a new session token.

Google charges a fee for autocomplete sessions that don't result in a detail request. So you definitely don't want to generate a new token on each keystroke!

See this:
https://developers.google.com/places/web-service/usage-and-billing#ac-per-request

And this:
https://developers.google.com/places/web-service/usage-and-billing#ac-no-details-session

**Comment by TroyWolf** [comment]
@GWSzeto, it is supposed to send an API request on every keystroke--that is how autocomplete does it's magic.

This issue is about using a new session token for every keystroke. If I understand Google's pricing model correctly (linked in my previous post), by default react-places-autocomplete will be racking up a ton of API charges for people!

It should generate a session token and use it until a detail request is made--then create a new session token if a subsequent autocomplete session is started.

> **About Autocomplete sessions**
An Autocomplete session includes some Autocomplete requests (to retrieve suggestions on a place as the user types), and at most one Places Details request (to retrieve details about the place selected by the user). The same session token is passed to the Autocomplete and the subsequent Place Detail request. A session starts with the first Autocomplete request (which typically happens when the user starts typing). A Places Details call is made when the user has selected one of the Autocomplete suggestions. If a user does not select a suggestion, no Places Details call is made.

> After a user has selected a place (a Places Details call is made), you must start a new session using a new session token.

**Comment by jmayergit** [comment]
It's not intended to be easily understood I think, the Google Pricing sheet.

The options are 70,000 requests vs 11,000 sessions. If you use session tokens you have 11,000 free sessions, assuming this is the only google service you use. If you don't use session tokens you have 70,000 free requests.

I'm just using the Places Autocomplete for my project and don't think I'm using the Places Detail API. So not using session tokens is okay for me especially if a session is <= 6 keystrokes.

**Comment by michebble** [comment]
When using `sessionToken`, it's important to keep in mind that it is invalidated after 3 minutes from  the first call to the Place Autocomplete API, or once a selection has been made. My understanding is that if your user continues to use an invalidated token, you will be charged as if you are not using a `sessionToken`.

Also, @jmayergit if your implementation supplies the `onSelect` function and you are using it to geocode, then you are making a call to Places Detail API. Just keep an eye on your usage details in the developer console.

**Comment by sambokai** [comment]
Any further observations on this? I’d like to prioritize this issue in case it affects pricing as much as suspected.

**Comment by sambokai** [comment]
Let's merge this conversation into #174. It seems to me that both are about the same problem. @mkoci let me know if you disagree and think this one warrants it's own issue. I'll close until then.

**Comment by sambokai** [comment]
Ok after further investigation it seems as if the issue I've linked is related but is not exactly about the same problem.

I still don't see any action point on this particular issue, however. You can generate a session token  and include it in the `searchOptions` and use that same token in your place details request in order to conclude the session. Once the user starts typing again it counts as a new session as per Google's definition and you'll need to provide a new session token. 

I'll leave the issue closed.

**Comment by cbovis** [comment]
@michebble it's been a while since you commented but I was wondering if you had a reference for this: "it's important to keep in mind that it is invalidated after 3 minutes"? I've trawled the official docs and can't see any reference to it.
